In [5]:
"""
1a. Modify the code below to count 'down' in increments of -1 (5 points)
"""
for word in range(0, 100):
    print (100-word)

100
99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1

In [6]:
"""
1b. Change the code above to count down in increments of -0.5 (5 points)
"""
for word in range(0, 100):
    print (100-word/2)

100.0
99.5
99.0
98.5
98.0
97.5
97.0
96.5
96.0
95.5
95.0
94.5
94.0
93.5
93.0
92.5
92.0
91.5
91.0
90.5
90.0
89.5
89.0
88.5
88.0
87.5
87.0
86.5
86.0
85.5
85.0
84.5
84.0
83.5
83.0
82.5
82.0
81.5
81.0
80.5
80.0
79.5
79.0
78.5
78.0
77.5
77.0
76.5
76.0
75.5
75.0
74.5
74.0
73.5
73.0
72.5
72.0
71.5
71.0
70.5
70.0
69.5
69.0
68.5
68.0
67.5
67.0
66.5
66.0
65.5
65.0
64.5
64.0
63.5
63.0
62.5
62.0
61.5
61.0
60.5
60.0
59.5
59.0
58.5
58.0
57.5
57.0
56.5
56.0
55.5
55.0
54.5
54.0
53.5
53.0
52.5
52.0
51.5
51.0
50.5

In [7]:
"""
2. Using list comprehension (HINT: []) populate an array whose individual word 
character lengths are >= 4 (10 points)
"""
the_sentence = 'the student went above and beyond the call of duty on the homework'

my_ar = list()
for word in the_sentence.split():
    if len(word) >= 4:
        my_ar.append(word)
my_ar_redux = [word for word in the_sentence.split() if len(word) >= 4]
print (my_ar_redux)

['student', 'went', 'above', 'beyond', 'call', 'duty', 'homework']

In [8]:
"""
3. Fix the errors in the code below and replace the word dog with turtle (10 points)
"""
import re
the_sentence = 'the orange cat jumped over the dog, but the orange cat landed on another orange cat'

my_ar = my_ar = re.sub('dog', 'turtle', the_sentence)

print(my_ar)

the orange cat jumped over the turtle, but the orange cat landed on another orange cat

In [9]:
"""
4. Remove all special characters from the sentence except for @ (10 points)
"""
the_sentence = 'woah!!! the @student really^ #impressed me, and& so did ??you!!!'
cleaned_text = re.sub("[!#?^#&]+","", the_sentence )
print (cleaned_text)

woah the @student really impressed me, and so did you

In [10]:
"""
5. create a sentence, each word seperated by one space, out of the following array 
and replace any special characters with a no space, except '!', with '' (10 points)
"""
the_ar = ['woah ! ! !','the','@student','really^','#impressed','me,','and&','so','did','??you ! ! !']
the_ar_to_str = ' '.join(the_ar)
cleaned_text= re.sub("[@^#&?]+","",the_ar_to_str)
print(cleaned_text)

woah ! ! ! the student really impressed me, and so did you ! ! !

In [11]:
"""
6. Create a program that loops 10 times and for each loop generate a random integer between 1 and 10, 
and print 'even' if the number is even and 'odd' if the number is odd (HINT: import random)
if the number is odd (10 points)
"""
import random 
for i in range (0,10):
    value = random.randint(0,10)
    if value%2 ==0:
        print (value, "is even")
    elif value%2 ==1:
        print (value, "is odd")
    else: 
        print ("Error, Invalid input")

6 is even
9 is odd
10 is even
3 is odd
4 is even
5 is odd
2 is even
4 is even
7 is odd
9 is odd

In [12]:
"""  
7. Create a program that counts the length of each word in an arbitrary sentence and stores 
each word and count pair in a pandas dataframe where one column is the word and one column is the 
word length (number of characters) (10 points)
"""
import pandas as pd 
my_pd = pd.DataFrame()
display (my_pd)

the_text = "in practice, it can turn out to be more effective to help the machine develop its own algorithm, rather than having human programmers specify every needed step."
def word_len(str_in):
    tmp = str_in.split()
    tmp_list = list(tmp)
    return tmp_list

words = word_len(the_text)
my_dictionary = dict()    

for word in words:
    my_pd = my_pd.append({"word": word, "length":len(word)}, ignore_index=True)
display (my_pd)

Empty DataFrame
Columns: []
Index: []

    length         word
0      2.0           in
1      9.0    practice,
2      2.0           it
3      3.0          can
4      4.0         turn
5      3.0          out
6      2.0           to
7      2.0           be
8      4.0         more
9      9.0    effective
10     2.0           to
11     4.0         help
12     3.0          the
13     7.0      machine
14     7.0      develop
15     3.0          its
16     3.0          own
17    10.0   algorithm,
18     6.0       rather
19     4.0         than
20     6.0       having
21     5.0        human
22    11.0  programmers
23     7.0      specify
24     5.0        every
25     6.0       needed
26     5.0        step.

In [13]:
"""
8. Replace the word cat with mouse (10 points)
"""
the_sentence = 'the cat jumped over the dog, but the cat landed on another cat!'
the_sentence.replace('cat','mouse')

'the mouse jumped over the dog, but the mouse landed on another mouse!'

In [14]:
"""
9. Cleanse the following sentence by removing all special characters 
except when the hyphen joins to two words and exclamation points (10 points)
"""

the_sentence = 'The impact*of data-driven$^%&marketing approaches!!'
cleanse_text= re.sub("[@*$^%&]+"," ",the_sentence)
print(cleanse_text)

The impact of data-driven marketing approaches!!

In [15]:
"""
10. Write a python program that inputs the sentence below and returns a dictionary
that has each unique character as a key and count of that character as the value.
(10 points)
"""

the_sentence = 'Everything flows, and nothing abides, everything gives way, and nothing stays fixed'

tokenize_text = list(the_sentence) 

def unique_characters(var_in):
    tmp = set(var_in)
    tmp_list = list (tmp)
    return tmp_list
characters = unique_characters(the_sentence)
my_dictionary = dict()
    
for char in characters:
    my_dictionary[char] = tokenize_text.count(char)
    
print(my_dictionary)

{'y': 4, 'n': 8, ',': 3, 'o': 3, 'i': 7, 's': 5, 'x': 1, 'd': 4, 'w': 2, 't': 5, 'b': 1, 'e': 6, 'r': 2, 'E': 1, 'g': 5, 'a': 5, ' ': 11, 'v': 3, 'f': 2, 'l': 1, 'h': 4}